"""Tests for ProvenanceGuard — metadata, hash integrity, disclosure, model allowlist."""

import hashlib
import pytest
from datetime import datetime, timezone, timedelta
from qwed_legal.guards.provenance_guard import ProvenanceGuard, ProvenanceRecord


SAMPLE_CONTENT = (
    "This document was generated by an AI model. "
    "The contract analysis shows the indemnification clause is standard."
)
SAMPLE_HASH = hashlib.sha256(SAMPLE_CONTENT.encode("utf-8")).hexdigest()
SAMPLE_TIMESTAMP = datetime.now(timezone.utc).isoformat()


def _make_provenance(**overrides):
    base = {
        "content_hash": SAMPLE_HASH,
        "model_id": "claude-4.5-sonnet",
        "generation_timestamp": SAMPLE_TIMESTAMP,
    }
    base.update(overrides)
    return base


@pytest.fixture
def guard() -> ProvenanceGuard:
    return ProvenanceGuard()


# ── Happy path ──────────────────────────────────────────────

class TestVerifyProvenanceSuccess:

    def test_valid_provenance(self, guard: ProvenanceGuard):
        result = guard.verify_provenance(SAMPLE_CONTENT, _make_provenance())
        assert result["verified"] is True
        assert "metadata_completeness" in result["checks_passed"]
        assert "hash_integrity" in result["checks_passed"]

    def test_valid_with_various_disclosure_phrases(self, guard: ProvenanceGuard):
        phrases = [
            "This content was generated by AI.",
            "Produced using artificial intelligence.",
            "Machine-generated analysis.",
            "AI-generated report for review.",
            "This document was produced by an LLM.",
        ]
        for phrase in phrases:
            h = hashlib.sha256(phrase.encode("utf-8")).hexdigest()
            ts = datetime.now(timezone.utc).isoformat()
            result = guard.verify_provenance(
                phrase,
                {"content_hash": h, "model_id": "test", "generation_timestamp": ts},
            )
            assert result["verified"] is True, f"Failed for: {phrase}"


# ── Metadata checks ────────────────────────────────────────

class TestMetadataCompleteness:

    def test_missing_model_id(self, guard: ProvenanceGuard):
        prov = _make_provenance()
        del prov["model_id"]
        result = guard.verify_provenance(SAMPLE_CONTENT, prov)
        assert result["verified"] is False
        assert result["risk"] == "INCOMPLETE_PROVENANCE"
        assert "metadata_completeness" in result["checks_failed"]

    def test_empty_content_hash(self, guard: ProvenanceGuard):
        result = guard.verify_provenance(
            SAMPLE_CONTENT, _make_provenance(content_hash="")
        )
        assert result["verified"] is False

    def test_missing_timestamp(self, guard: ProvenanceGuard):
        prov = _make_provenance()
        del prov["generation_timestamp"]
        result = guard.verify_provenance(SAMPLE_CONTENT, prov)
        assert result["verified"] is False


# ── Hash integrity ──────────────────────────────────────────

class TestHashIntegrity:

    def test_tampered_content(self, guard: ProvenanceGuard):
        """Hash was computed on original, but content was changed."""
        tampered = SAMPLE_CONTENT + " INJECTED TEXT"
        result = guard.verify_provenance(tampered, _make_provenance())
        assert result["verified"] is False
        assert result["risk"] == "CONTENT_TAMPERED"
        assert "hash_integrity" in result["checks_failed"]

    def test_wrong_hash(self, guard: ProvenanceGuard):
        result = guard.verify_provenance(
            SAMPLE_CONTENT,
            _make_provenance(content_hash="0000000000000000000000000000000000000000000000000000000000000000"),
        )
        assert result["verified"] is False
        assert "hash_integrity" in result["checks_failed"]


# ── Disclosure checks ──────────────────────────────────────

class TestDisclosureCompliance:

    def test_missing_disclosure(self, guard: ProvenanceGuard):
        content = "The indemnification clause caps liability at $1M."
        h = hashlib.sha256(content.encode("utf-8")).hexdigest()
        result = guard.verify_provenance(
            content,
            _make_provenance(content_hash=h),
        )
        assert result["verified"] is False
        assert result["risk"] == "MISSING_DISCLOSURE"
        assert "disclosure_present" in result["checks_failed"]

    def test_disclosure_not_required(self):
        guard = ProvenanceGuard(require_disclosure=False)
        content = "No disclosure here."
        h = hashlib.sha256(content.encode("utf-8")).hexdigest()
        result = guard.verify_provenance(
            content,
            {"content_hash": h, "model_id": "test",
             "generation_timestamp": datetime.now(timezone.utc).isoformat()},
        )
        assert result["verified"] is True
        assert "disclosure_present" not in result["checks_passed"]


# ── Model allowlist ─────────────────────────────────────────

class TestModelAllowlist:

    def test_unauthorized_model(self):
        guard = ProvenanceGuard(allowed_models=["gpt-4o", "claude-4.5-sonnet"])
        result = guard.verify_provenance(
            SAMPLE_CONTENT,
            _make_provenance(model_id="unknown-model-v1"),
        )
        assert result["verified"] is False
        assert result["risk"] == "UNAUTHORIZED_MODEL"
        assert "model_allowed" in result["checks_failed"]

    def test_authorized_model(self):
        guard = ProvenanceGuard(allowed_models=["gpt-4o", "claude-4.5-sonnet"])
        result = guard.verify_provenance(SAMPLE_CONTENT, _make_provenance())
        assert result["verified"] is True
        assert "model_allowed" in result["checks_passed"]

    def test_empty_allowlist_denies_all(self):
        """Empty list means deny-all, not allow-all."""
        guard = ProvenanceGuard(allowed_models=[])
        result = guard.verify_provenance(SAMPLE_CONTENT, _make_provenance())
        assert result["verified"] is False
        assert "model_allowed" in result["checks_failed"]


# ── Human review ────────────────────────────────────────────

class TestHumanReview:

    def test_unreviewed_content_flagged(self):
        guard = ProvenanceGuard(require_human_review=True)
        result = guard.verify_provenance(
            SAMPLE_CONTENT, _make_provenance(human_reviewed=False)
        )
        assert result["verified"] is False
        assert result["risk"] == "UNREVIEWED_CONTENT"

    def test_reviewed_content_passes(self):
        guard = ProvenanceGuard(require_human_review=True)
        result = guard.verify_provenance(
            SAMPLE_CONTENT,
            _make_provenance(human_reviewed=True, reviewer_id="legal-team"),
        )
        assert result["verified"] is True


# ── Edge cases ──────────────────────────────────────────────

class TestEdgeCases:

    def test_empty_content(self, guard: ProvenanceGuard):
        result = guard.verify_provenance("", _make_provenance())
        assert result["verified"] is False
        assert result["risk"] == "INVALID_CONTENT"

    def test_non_dict_provenance(self, guard: ProvenanceGuard):
        result = guard.verify_provenance(SAMPLE_CONTENT, "not-a-dict")  # type: ignore[arg-type]
        assert result["verified"] is False
        assert result["risk"] == "INVALID_PROVENANCE"

    def test_future_timestamp_rejected(self, guard: ProvenanceGuard):
        future = (datetime.now(timezone.utc) + timedelta(hours=1)).isoformat()
        result = guard.verify_provenance(
            SAMPLE_CONTENT,
            _make_provenance(generation_timestamp=future),
        )
        assert result["verified"] is False
        assert "timestamp_valid" in result["checks_failed"]

    def test_invalid_timestamp_format(self, guard: ProvenanceGuard):
        result = guard.verify_provenance(
            SAMPLE_CONTENT,
            _make_provenance(generation_timestamp="not-a-date"),
        )
        assert result["verified"] is False
        assert "timestamp_valid" in result["checks_failed"]


# ── Generate provenance ─────────────────────────────────────

class TestGenerateProvenance:

    def test_generate_returns_record(self):
        guard = ProvenanceGuard()
        record = guard.generate_provenance(
            content="Test content",
            model_id="claude-4.5-sonnet",
            disclosure_text="AI-generated",
        )
        assert isinstance(record, ProvenanceRecord)
        assert record.model_id == "claude-4.5-sonnet"
        assert record.content_hash == hashlib.sha256(b"Test content").hexdigest()
        assert record.human_reviewed is False

    def test_generated_provenance_verifies(self):
        guard = ProvenanceGuard(require_disclosure=False)
        content = "Test legal analysis output."
        record = guard.generate_provenance(content, model_id="gpt-4o")
        prov = {
            "content_hash": record.content_hash,
            "model_id": record.model_id,
            "generation_timestamp": record.generation_timestamp,
        }
        result = guard.verify_provenance(content, prov)
        assert result["verified"] is True
